# Generated by Django 3.2.9 on 2021-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='payments', to='billing.Order', verbose_name='Commande'),
        ),
    ]
