# Generated by Django 3.2.9 on 2021-12-01 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_auto_20211201_1151'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='bar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.bar', verbose_name='Boisson de bar'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='goodies_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.goodies', verbose_name='Goodies'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='miscellaneous_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.miscellaneous', verbose_name='Autre article divers'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderlines', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
