# Generated by Django 3.2.9 on 2021-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Facture'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de la facture'),
        ),
    ]
