# Generated by Django 3.2.9 on 2021-11-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_done',
        ),
    ]
