# Generated by Django 3.2.9 on 2021-11-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20211127_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(related_name='payments', to='billing.Order', verbose_name='commande'),
        ),
    ]
