# Generated by Django 3.2.9 on 2021-12-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20211202_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderlines', to='billing.bill', verbose_name='Facture'),
        ),
    ]
