# Generated by Django 3.2.9 on 2021-12-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20211201_1151'),
        ('schedule', '0005_auto_20211201_1147'),
        ('billing', '0002_auto_20211201_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='bar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.bar', verbose_name='Boisson de bar'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='goodies_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.goodies', verbose_name='Goodies'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='schedule.guest', verbose_name='Passager.ère'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='miscellaneous_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.miscellaneous', verbose_name='Autre article divers'),
        ),
    ]
