# Generated by Django 3.2.9 on 2021-12-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('billing', '0003_alter_orderline_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='bar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.bar', verbose_name='Boisson de bar'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='goodies_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.goodies', verbose_name='Goodies'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='miscellaneous_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='stocks.miscellaneous', verbose_name='Autre article divers'),
        ),
    ]
