# Generated by Django 3.2.9 on 2021-12-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20211202_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='payment_date',
        ),
    ]
