# Generated by Django 3.2.9 on 2021-12-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('billing', '0005_auto_20211206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='schedule.trip', verbose_name='Voyage'),
        ),
    ]
