# Generated by Django 3.2.9 on 2021-12-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('billing', '0006_orderline_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlines', to='schedule.trip', verbose_name='Voyage'),
        ),
    ]
