# Generated by Django 3.2.9 on 2021-12-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_bill_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billpaid',
            options={'verbose_name': 'Facture payée', 'verbose_name_plural': 'Factures payées'},
        ),
        migrations.AlterModelOptions(
            name='invoicedorder',
            options={'verbose_name': 'Commande facturée', 'verbose_name_plural': 'Commandes facturées'},
        ),
    ]
