# Generated by Django 3.2.9 on 2021-12-18 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0010_auto_20211213_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_eur', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Taux de change USD-EUR')),
                ('usd_idr', models.PositiveSmallIntegerField(verbose_name='Taux de change USD-IDR')),
                ('credit_card_fee', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Frais de carte de crédit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Taux de change',
            },
        ),
    ]
