# Generated by Django 3.2.9 on 2021-12-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Taux de change', 'verbose_name_plural': 'Taux de change'},
        ),
    ]
