# Generated by Django 3.2.9 on 2021-12-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20211219_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='credit_card_fee',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.05, max_digits=5, null=True, verbose_name='Frais de carte de crédit'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usd_eur',
            field=models.DecimalField(decimal_places=4, default=0.89, max_digits=6, verbose_name='Taux de change USD-EUR'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usd_idr',
            field=models.PositiveSmallIntegerField(default=14386, verbose_name='Taux de change USD-IDR'),
        ),
    ]
