# Generated by Django 3.2.9 on 2021-12-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_bar_related', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='goodies',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_goodies_related', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_kitchen_related', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_miscellaneous_related', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bar_final_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.bar', verbose_name='stock final de boisson'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bar_initial_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.bar', verbose_name='stock initial de boisson'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goodies_final_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.goodies', verbose_name='stock final de goodies'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goodies_initial_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.goodies', verbose_name='stock initial de goodies'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kitchen_final_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.kitchen', verbose_name='stock final de nourriture'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kitchen_initial_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.kitchen', verbose_name='stock initial de nourriture'),
        ),
    ]
