# Generated by Django 3.2.9 on 2021-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('stocks', '0002_alter_goodies_goodies_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_item', models.CharField(choices=[('Bootle & Can', 'Bootle & Can'), ('Food', 'Food'), ('Goodies', 'Goodies')], max_length=20, verbose_name="Type d'article")),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trips', models.ManyToManyField(related_name='stocks', to='schedule.Trip', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Stock',
            },
        ),
    ]
