# Generated by Django 3.2.9 on 2021-12-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bar_final_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.bar', verbose_name='stock final de boisson'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bar_initial_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.bar', verbose_name='stock initial de boisson'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goodies_final_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.goodies', verbose_name='stock final de goodies'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goodies_initial_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.goodies', verbose_name='stock initial de goodies'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kitchen_final_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_final_related', to='stocks.kitchen', verbose_name='stock final de nourriture'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kitchen_initial_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocks_stock_initial_related', to='stocks.kitchen', verbose_name='stock initial de nourriture'),
        ),
    ]
