# Generated by Django 3.2.9 on 2021-12-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20211201_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['bar_category', 'name'], 'verbose_name': 'Boisson'},
        ),
        migrations.AlterModelOptions(
            name='goodies',
            options={'ordering': ['goodies_category', 'name'], 'verbose_name': 'Goodie'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ['food_category', 'name'], 'verbose_name': 'Nourriture'},
        ),
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'ordering': ['name'], 'verbose_name': 'Autres articles diver'},
        ),
    ]
