# Generated by Django 3.2.9 on 2021-12-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20211209_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialBarStock',
            fields=[
            ],
            options={
                'verbose_name': 'Stock initial du bar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stocks.stock',),
        ),
    ]
