# Generated by Django 3.2.9 on 2021-12-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20211213_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['bar_category', 'name'], 'verbose_name': 'Boisson du bar', 'verbose_name_plural': 'Boissons du bar'},
        ),
        migrations.AlterModelOptions(
            name='finalbarstock',
            options={'verbose_name': 'Stock final du bar', 'verbose_name_plural': 'Stocks finaux du bar'},
        ),
        migrations.AlterModelOptions(
            name='finalgoodiesstock',
            options={'verbose_name': 'Stock final de goodies', 'verbose_name_plural': 'Stocks finaux de goodies'},
        ),
        migrations.AlterModelOptions(
            name='finalkitchenstock',
            options={'verbose_name': 'Stock final de la cuisine', 'verbose_name_plural': 'Stocks finaux de la cuisine'},
        ),
        migrations.AlterModelOptions(
            name='goodies',
            options={'ordering': ['goodies_category', 'name'], 'verbose_name': 'Goody', 'verbose_name_plural': 'Goodies'},
        ),
        migrations.AlterModelOptions(
            name='initialbarstock',
            options={'verbose_name': 'Stock initial du bar', 'verbose_name_plural': 'Stocks initiaux du bar'},
        ),
        migrations.AlterModelOptions(
            name='initialgoodiesstock',
            options={'verbose_name': 'Stock initial de goodies', 'verbose_name_plural': 'Stocks initiaux de goodies'},
        ),
        migrations.AlterModelOptions(
            name='initialkitchenstock',
            options={'verbose_name': 'Stock initial de la cuisine', 'verbose_name_plural': 'Stocks initiaux de la cuisine'},
        ),
        migrations.AlterModelOptions(
            name='miscellaneous',
            options={'ordering': ['name'], 'verbose_name': 'Autre article divers', 'verbose_name_plural': 'Autres articles divers'},
        ),
    ]
