# Generated by Django 3.2.9 on 2021-11-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('first_name', 'last_name')},
        ),
    ]
