# Generated by Django 3.2.9 on 2021-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_guest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.PositiveSmallIntegerField(verbose_name='Durée du voyage en jours'),
        ),
    ]
