# Generated by Django 3.2.9 on 2021-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_trip_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, verbose_name='Genre'),
        ),
    ]
